apiVersion: v1
kind: ConfigMap
metadata:
  name: bonds
  namespace: asi-chain
data:
  bonds.txt: |
    REPLACE_V1_PUBKEY 100000
    REPLACE_V2_PUBKEY 100000
    REPLACE_V3_PUBKEY 100000
    REPLACE_V4_PUBKEY 1
