apiVersion: v1
kind: Service
metadata:
  name: validator
  namespace: asi-chain
  labels:
    app: asi-chain
    role: validator
spec:
  type: NodePort
  selector:
    app: asi-chain
    role: validator
  ports:
    - name: p2p
      port: 40400
      targetPort: 40400
      nodePort: 30000
      protocol: TCP
    - name: grpc-ext
      port: 40401
      targetPort: 40401
      nodePort: 30001
      protocol: TCP
    - name: grpc-int
      port: 40402
      targetPort: 40402
      nodePort: 30002
      protocol: TCP
    - name: http
      port: 40403
      targetPort: 40403
      nodePort: 30003
      protocol: TCP
    - name: kademlia
      port: 40404
      targetPort: 40404
      nodePort: 30004
      protocol: TCP
    - name: http-admin
      port: 40405
      targetPort: 40405
      nodePort: 30005
      protocol: TCP
