# Remove named volumes on docker compose down to ensure fresh state on next up
compose_down_flags: "-v"

compose_jobs:
  - name: "validator1 and validator2"
    work_dir: ~/actual-dev-chain
    compose_file: v1-v2.yml

local_containers:
  - validator1
  - validator2
