# Remove named volumes on docker compose down to ensure fresh state on next up
compose_down_flags: "-v"

compose_jobs:
  - name: observer
    work_dir: ~/observer
    compose_file: observer.yml

observer_containers:
  - observer

observer_http_port: 40453
