
services:
  connector:
    image: connector:latest
    environment:
      - FAUCET_API_URL=https://asi-testnet-faucet.singularitynet.io
      - BOOTSTRAP_PUBLIC_GRPC_PORT=40401
      - OBSERVER_INTERNAL_GRPC_PORT=40452
      - STAKE=100000000
    volumes:
      - ./.env:/app/.env
