name: validator

x-rnode: &default-rnode
  image: amamata/snet-scala-node:optimized
  user: root
  networks:
    - f1r3fly

services:
  connector:
    image: 533793137436.dkr.ecr.us-east-1.amazonaws.com/asi-chain/validator-connector:v0.0.2
    container_name: validator-connector-job
    env_file: .env
    restart: "no"
  validator:
    <<: *default-rnode
    container_name: validator
    environment:
      - JAVA_OPTS=-Xss16m -XX:+UseG1GC -XX:MaxGCPauseMillis=200
      - SBT_OPTS=-Xmx4g -Xss2m -Dsbt.supershell=false
    command:
      [
        "run",
        "--host=$VALIDATOR_HOST",
        "--protocol-port=40440",
        "--api-port-grpc-external=40441",
        "--api-port-grpc-internal=40442",
        "--api-port-http=40443",
        "--discovery-port=40444",
        "--api-port-admin-http=40445",
        "--bootstrap=$BOOTSTRAP",
        "--validator-public-key=$VALIDATOR_PUBLIC_KEY",
        "--validator-private-key=$VALIDATOR_PRIVATE_KEY"
      ]
    ports:
      - "40440:40440"
      - "40441:40441"
      - "40442:40442"
      - "40443:40443"
      - "40444:40444"
      - "40445:40445"
    volumes:
      - ./conf/validator.conf:/var/lib/rnode/rnode.conf
      - ./conf/logback.xml:/var/lib/rnode/logback.xml
      - ./data:/var/lib/rnode/

networks:
  f1r3fly:
    external: false
    name: docker_f1r3fly
